In [45]:
import numpy as np 
import pandas as pd 
import os.path as op  
import datetime as dt 
import scipy
import time 

# The default data directory will be '../../data' 
# This can be redefined by the user of the function. 
data_dir = op.join('data') 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
import massflow_baseline

In [3]:
raw = massflow_baseline.get_data()

In [17]:
raw.head()

,Authority,Period,QuestionNumber,QuText,RowText,ColText,Data,MaterialGroup
0,Flintshire County Council,Jan 15 - Mar 15,Q001,Authority Data: Note this data is prefilled.,Population of Authority,NaN,149700,NaN
1,Flintshire County Council,Jan 15 - Mar 15,Q002,Authority Data: Note this data is prefilled.,Number of Households,NaN,65650,NaN
2,Flintshire County Council,Jan 15 - Mar 15,Q002,Authority Data: Note this data is prefilled.,Dwelling Stock,NaN,65366,NaN
3,Flintshire County Council,Jan 15 - Mar 15,Q002,Authority Data: Note this data is prefilled.,BMW % Conversion factor,NaN,61,NaN
4,Flintshire County Council,Jan 15 - Mar 15,Q002,Authority Data: Note this data is prefilled.,MBT Reduction Factor (Apr 2009 on),NaN,1,NaN

In [51]:
pop_qtr = raw[(raw.QuestionNumber == 'Q001') & (raw.RowText == 'Population of Authority')]
pop_qtr
pop_la = pop_qtr[['Authority','Data']].drop_duplicates().rename(columns={'Data':'Population'})
pop_la = pop_la.sort('Authority').reset_index().drop('index', axis=1)

#Definition
"The definition of commercial wastes in this study includes all waste from non-household sources. This includes beverage containers deposited in refuse or recycling schemes from commercial or industrial enterprises."

First, let's explore whether question 11 about commercial waste has sufficient data?

In [4]:
pd.crosstab([raw['QuText'], raw['QuestionNumber']], raw['ColText'])

,ColText,% recycled by dismantler,Collected Co-mingled?,Destination of residual,No of segregated litter bins by material type,No. of LA bring sites by material type,No. of households receiving a collection,Number,Percentage weighed,Proportion of which construction & demolition waste,Tonnage,Tonnage Collected for Reuse,Tonnage Collected for recycling,Tonnage Collected for reuse but actually rejected / disposed,Tonnage collected for recycling,Tonnage collected for recycling but actually rejected / disposed,Tonnage collected for recycling but actually rejected/disposed,Tonnage collected for reuse,Tonnage collected for reuse but actually rejected / disposed,Tonnage collected for reuse but actually rejected/disposed,Tonnage from household Sources
QuText,QuestionNumber,,,,,,,,,,,,,,,,,,,,
Composting / Recycling tonnage collected through any other recycling schemes. Please note that it is optional to report how much of the total tonnage is from household sources - please see Help for further information.,Q018,0,0,0,0,0,0,0,0,0,51,0,0,0,0,0,0,0,0,0,8
How many abandoned vehicles were disposed of by your authority and what percentage was recycled?,Q025,29,0,0,0,0,0,40,0,0,31,0,0,0,0,0,0,0,0,0,0
Please provide details of other waste collected for disposal. (The destination of the residual is required for authorities in Wales only.),Q023,0,0,642,0,0,0,0,568,19,647,0,0,0,0,0,0,0,0,0,0
"Tonnes of material collected from commercial, industrial or other non household sources by LA or its contractors",Q011,0,198,0,0,0,0,0,0,0,0,16,0,12,293,0,29,0,0,0,0
Tonnes of material collected through kerbside schemes by non contracted voluntary/community sector from household sources,Q012,0,52,0,0,0,0,0,0,0,0,112,0,6,30,0,1,0,0,0,0
Tonnes of material collected at bring sites operated by LA or its contractors,Q017,0,0,0,0,124,0,0,0,0,0,0,0,0,341,52,0,109,40,0,0
Tonnes of material collected for recycling at street recycling bins,Q034,0,0,0,1,0,0,0,0,0,0,0,0,0,5,0,1,1,0,1,0
Tonnes of material collected for recycling/reuse at CA Sites operated by LA or its contractors,Q016,0,0,0,0,0,0,0,0,0,0,0,0,0,1910,248,0,334,158,0,0
Tonnes of material collected through kerbside schemes from household sources by LA or its contractors,Q010,0,414,0,0,0,352,0,0,0,0,41,0,11,534,0,31,0,0,0,0
Tonnes of materials collected at bring sites operated by voluntary / community sector,Q033,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,10,0,0,0

#Commercial recycling

In [5]:
com = raw[(raw.QuestionNumber == 'Q011')]
com.ColText.unique()

array([u'Tonnage collected for recycling', u'Collected Co-mingled?',
       u'Tonnage Collected for Reuse',
       u'Tonnage collected for recycling but actually rejected/disposed',
       u'Tonnage Collected for reuse but actually rejected / disposed'], dtype=object)

In [71]:
raw[(raw.QuestionNumber == 'Q011') & (raw.ColText == 'Tonnage Collected for Reuse') 
    & raw.Data >0]

,Authority,Period,QuestionNumber,QuText,RowText,ColText,Data,MaterialGroup
328,Flintshire County Council,Apr 14 - Jun 14,Q011,"Tonnes of material collected from commercial,...",Rubble,Tonnage Collected for Reuse,252.77,Rubble
2290,Newport City Council,Jan 15 - Mar 15,Q011,"Tonnes of material collected from commercial,...",WEEE - Small Domestic App,Tonnage Collected for Reuse,14.86,WEEE
2292,Newport City Council,Jan 15 - Mar 15,Q011,"Tonnes of material collected from commercial,...",Ink & toner cartridges,Tonnage Collected for Reuse,2.48,Composite
2299,Newport City Council,Jan 15 - Mar 15,Q011,"Tonnes of material collected from commercial,...",Furniture,Tonnage Collected for Reuse,29.4,Furniture

In [6]:
com_rec = raw[(raw.QuestionNumber == 'Q011') & 
                     (raw.ColText == 'Tonnage collected for recycling')]
com_rec_qtr = com_rec.pivot_table(values='Data', index=['Authority','Period'],
                                         columns='RowText', aggfunc = lambda x: x).reset_index()
com_rec_qtr

RowText,Authority,Period,Automotive batteries,Car tyres,Card,Co mingled materials,Composite wood materials,Gas bottles,Green garden waste only,Ink & toner cartridges,Mineral Oil,Mixed Plastic Bottles,Mixed cans,Mixed glass,Mixed paper & card,Mixed tyres,OTHER PLASTICS [7],Other Scrap metal,Other compostable waste,Other materials,Paper,Plasterboard,Plastics,"Post consumer, non automotive batteries",Rubble,Soil,Textiles & footwear,WEEE - Cathode Ray Tubes,WEEE - Flourescent tubes and other light bulbs,WEEE - Fridges & Freezers,WEEE - Small Domestic App,Waste food only,Wood
0,Bridgend CBC,Apr 14 - Jun 14,NaN,0.64,4.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.56,0.63,19.32,NaN,NaN,10.50,NaN,NaN,NaN,NaN,4.07,NaN,NaN,67.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bridgend CBC,Jan 15 - Mar 15,NaN,0.02,3.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.48,2.76,15.39,NaN,NaN,13.24,NaN,NaN,NaN,NaN,4.44,NaN,NaN,14.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bridgend CBC,Jul 14 - Sep 14,NaN,0.02,4.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.55,NaN,20.03,NaN,NaN,7.14,NaN,NaN,NaN,NaN,4.55,NaN,NaN,70.25,NaN,NaN,NaN,NaN,NaN,NaN,6.25
3,Bridgend CBC,Oct 14 - Dec 14,NaN,1.62,4.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.55,0.33,20.58,NaN,NaN,16.81,NaN,NaN,NaN,NaN,4.41,NaN,NaN,38.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Caerphilly CBC,Apr 14 - Jun 14,NaN,NaN,NaN,1351.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Caerphilly CBC,Jan 15 - Mar 15,NaN,NaN,NaN,1251.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Caerphilly CBC,Jul 14 - Sep 14,NaN,NaN,NaN,1411.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Caerphilly CBC,Oct 14 - Dec 14,NaN,NaN,NaN,1379.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Cardiff County Council,Apr 14 - Jun 14,NaN,NaN,0.38,922.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364.84,NaN
9,Cardiff County Council,Jan 15 - Mar 15,NaN,NaN,NaN,928.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.16,NaN,69.914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,376.33,NaN
10,Cardiff County Council,Jul 14 - Sep 14,NaN,NaN,0.20,947.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,321.160,2.020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,350.70,NaN
11,Cardiff County Council,Oct 14 - Dec 14,NaN,NaN,0.54,1027.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.66,NaN,49.863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,435.88,NaN
12,Carmarthenshire County Council,Apr 14 - Jun 14,NaN,NaN,26.98,47.00,NaN,NaN,3.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.460,NaN,0.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Carmarthenshire County Council,Jan 15 - Mar 15,NaN,NaN,NaN,120.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Carmarthenshire County Council,Jul 14 - Sep 14,NaN,NaN,0.28,26.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Carmarthenshire County Council,Oct 14 - Dec 14,NaN,NaN,NaN,109.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,City and County of Swansea,Apr 14 - Jun 14,NaN,NaN,428.39,338.14,NaN,NaN,256.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.64,NaN,NaN,NaN,38.44,18.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,243.52
17,City and County of Swansea,Jan 15 - Mar 15,NaN,NaN,612.05,279.21,NaN,NaN,240.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.53,NaN,NaN,748.070,46.02,18.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.22,137.95
18,City and County of Swansea,Jul 14 - Sep 14,NaN,NaN,428.43,448.40,NaN,NaN,238.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.36,NaN,NaN,NaN,41.80,21.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.03
19,City and County of Swansea,Oct 14 - Dec 14,NaN,NaN,482.14,477.70,NaN,NaN,736.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,731.260,37.30,13.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.85
20,Conwy CBC,Apr 14 - Jun 14,0.220,NaN,24.91,NaN,NaN,0.47,NaN,NaN,NaN,NaN,14.10,55.59,NaN,2.41,NaN,23.58,612.84,NaN,70.760,NaN,66.15,0.04,174.42,NaN,NaN,37.58,NaN,6.08,28.52,109.46,24.00
21,Conwy CBC,Jan 15 - Mar 15,NaN,NaN,30.10,NaN,NaN,0.81,NaN,NaN,1.2,NaN,11.51,43.78,NaN,1.10,NaN,28.32,197.89,NaN,57.190,NaN,5.02,NaN,186.20,NaN,NaN,3.46,NaN,4.72,43.16,127.58,24.00
22,Conwy CBC,Jul 14 - Sep 14,NaN,NaN,24.42,NaN,NaN,0.88,NaN,NaN,NaN,NaN,14.35,55.90,NaN,2.43,NaN,27.20,370.81,NaN,76.050,NaN,16.54,NaN,120.14,NaN,NaN,26.16,0.19,4.92,50.12,122.26,24.00
23,Conwy CBC,Oct 14 - Dec 14,0.490,NaN,17.62,NaN,NaN,0.09,NaN,NaN,NaN,NaN,12.22,48.18,NaN,2.63,NaN,21.34,449.00,NaN,61.940,NaN,8.85,NaN,123.46,NaN,NaN,4.92,0.11,5.44,17.12,86.30,24.00
24,Denbighshire County Council,Apr 14 - Jun 14,NaN,NaN,NaN,135.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Denbighshire County Council,Jan 15 - Mar 15,NaN,NaN,NaN,139.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Denbighshire County Council,Jul 14 - Sep 14,NaN,NaN,NaN,142.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Denbighshire County Council,Oct 14 - Dec 14,NaN,NaN,NaN,139.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Flintshire County Council,Apr 14 - Jun 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.11,NaN
29,Flintshire County Council,Jan 15 - Mar 15,NaN,NaN,NaN,148.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Flintshire County Council,Jul 14 - Sep 14,NaN,NaN,NaN,178.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Flintshire County Council,Oct 14 - Dec 14,NaN,NaN,NaN,171.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Gwynedd Council,Apr 14 - Jun 14,NaN,NaN,132.76,606.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,148.56,NaN,NaN,22.36,1.22,NaN,NaN,94.860,NaN,NaN,NaN,NaN,NaN,1.60,NaN,NaN,NaN,NaN,270.16,5.82
33,Gwynedd Council,Jan 15 - Mar 15,NaN,NaN,109.56,505.98,3.58,NaN,NaN,0.77,NaN,1.37,NaN,82.82,NaN,NaN,NaN,7.60,32.43,NaN,86.320,NaN,NaN,NaN,NaN,NaN,20.51,NaN,NaN,NaN,NaN,237.26,NaN
34,Gwynedd Council,Jul 14 - Sep 14,NaN,NaN,153.66,684.97,7.16,NaN,NaN,NaN,NaN,5.83,NaN,159.76,NaN,NaN,NaN,3.64,9.30,NaN,88.220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301.40,NaN
35,Gwynedd Council,Oct 14 - Dec 14,NaN,NaN,119.86,508.58,2.36,NaN,NaN,NaN,NaN,3.78,NaN,113.10,NaN,NaN,34.28,43.62,87.12,NaN,87.820,NaN,NaN,NaN,NaN,NaN,10.59,NaN,NaN,NaN,NaN,249.70,NaN
36,Merthyr Tydfil CBC,Apr 14 - Jun 14,NaN,NaN,39.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.60,82.52,NaN,NaN,NaN,NaN,NaN,NaN,2.193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.15,NaN,NaN
37,Merthyr Tydfil CBC,Jan 15 - Mar 15,NaN,NaN,41.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.60,102.06,NaN,NaN,NaN,NaN,NaN,NaN,4.460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Merthyr Tydfil CBC,Jul 14 - Sep 14,NaN,NaN,23.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.83,95.69,NaN,NaN,NaN,NaN,NaN,NaN,0.090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Merthyr Tydfil CBC,Oct 14 - Dec 14,NaN,NaN,22.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.79,84.99,NaN,NaN,NaN,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Neath Port Talbot CBC,Apr 14 - Jun 14,NaN,NaN,92.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.00,145.00,NaN,NaN,NaN,NaN,NaN,NaN,11.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Neath Port Talbot CBC,Jan 15 - Mar 15,NaN,NaN,92.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Neath Port Talbot CBC,Jul 14 - Sep 14,NaN,NaN,92.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Neath Port Talbot CBC,Oct 14 - Dec 14,NaN,NaN,92.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Newport City Council,Apr 14 - Jun 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.00,NaN,NaN,NaN,NaN,NaN,7.420,80.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Newport City Council,Jan 15 - Mar 15,NaN,NaN,NaN,6.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,371.85,NaN,NaN,NaN,NaN,NaN,NaN,16.660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Newport City Council,Jul 14 - Sep 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.00,NaN,NaN,NaN,NaN,NaN,NaN,80.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Newport City Council,Oct 14 - Dec 14,NaN,NaN,NaN,5.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.00,NaN,NaN,NaN,NaN,NaN,NaN,89.680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Pembrokeshire County Council,Apr 14 - Jun 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.10,NaN,NaN,NaN,19.08,NaN,NaN,20.630,6.64,NaN,NaN,252.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Pembrokeshire County Council,Jan 15 - Mar 15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.02,NaN,NaN,NaN,33.52,NaN,NaN,3.440,NaN,NaN,NaN,94.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Pembrokeshire County Council,Jul 14 - Sep 14,NaN,NaN,2.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.79,NaN,NaN,NaN,19.14,NaN,NaN,30.380,NaN,NaN,NaN,168.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Pembrokeshire County Council,Oct 14 - Dec 14,NaN,NaN,1.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.84,NaN,NaN,NaN,14.66,NaN,NaN,19.880,NaN,NaN,NaN,82.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Powys County Council,Jan 15 - Mar 15,0.958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Powys County Council,Jul 14 - Sep 14,0.403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Rhondda Cynon Taff CBC,Apr 14 - Jun 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Rhondda Cynon Taff CBC,Jan 15 - Mar 15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Rhondda Cynon Taff CBC,Jul 14 - Sep 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Rhondda Cynon Taff CBC,Oct 14 - Dec 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Torfaen CBC,Apr 14 - Jun 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Torfaen CBC,Jan 15 - Mar 15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.775,NaN,NaN,NaN,NaN,28.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Torfaen CBC,Jul 14 - Sep 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Torfaen CBC,Oct 14 - Dec 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Wrexham CBC,Apr 14 - Jun 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.28,12.08,NaN,NaN,11.540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Wrexham CBC,Jan 15 - Mar 15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.58,2.26,NaN,NaN,8.860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Wrexham CBC,Jul 14 - Sep 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.50,9.50,NaN,NaN,11.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Wrexham CBC,Oct 14 - Dec 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.29,3.40,NaN,NaN,12.460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
com_rec_la = (com_rec_qtr.groupby('Authority').agg(np.sum).reset_index()
              .drop(['Green garden waste only','Waste food only'],axis=1))
#Generate the sum of recycling materials (mostly just 'Co mingled materials' if applicable to LAs)
com_rec_la['sum_dry_rec'] = com_rec_la.sum(axis=1)
com_rec_la = com_rec_la[['Authority','Mixed glass','Mixed Plastic Bottles',
                         'Plastics','Mixed cans','Co mingled materials','sum_dry_rec']]
com_rec_la

RowText,Authority,Mixed glass,Mixed Plastic Bottles,Plastics,Mixed cans,Co mingled materials,sum_dry_rec
0,Bridgend CBC,3.72,NaN,17.47,2.14,NaN,362.480
1,Caerphilly CBC,NaN,NaN,NaN,NaN,5394.67,5394.670
2,Cardiff County Council,NaN,NaN,NaN,NaN,3825.17,4442.687
3,Carmarthenshire County Council,NaN,NaN,0.72,NaN,303.80,382.880
4,City and County of Swansea,NaN,NaN,72.24,NaN,1543.45,5905.470
5,Conwy CBC,203.45,NaN,96.56,52.18,NaN,3391.650
6,Denbighshire County Council,NaN,NaN,NaN,NaN,556.83,556.830
7,Flintshire County Council,13.40,NaN,NaN,NaN,498.11,511.510
8,Gwynedd Council,504.24,10.98,NaN,NaN,2305.79,3988.030
9,Merthyr Tydfil CBC,365.26,NaN,NaN,47.82,NaN,549.943
10,Neath Port Talbot CBC,634.00,NaN,NaN,18.00,NaN,1031.000
11,Newport City Council,551.85,NaN,NaN,NaN,11.94,837.550
12,Pembrokeshire County Council,155.75,NaN,NaN,NaN,NaN,924.000
13,Powys County Council,NaN,NaN,NaN,NaN,NaN,21.101
14,Rhondda Cynon Taff CBC,NaN,NaN,NaN,NaN,NaN,41.210
15,Torfaen CBC,NaN,NaN,NaN,NaN,NaN,128.095
16,Wrexham CBC,NaN,NaN,NaN,NaN,NaN,84.150

In [52]:
merge = pop_la.merge(com_rec_la, how='left',on='Authority')
merge

,Authority,Population,Mixed glass,Mixed Plastic Bottles,Plastics,Mixed cans,Co mingled materials,sum_dry_rec
0,Blaenau Gwent CBC,68400,NaN,NaN,NaN,NaN,NaN,NaN
1,Bridgend CBC,134600,3.72,NaN,17.47,2.14,NaN,362.480
2,Caerphilly CBC,173100,NaN,NaN,NaN,NaN,5394.67,5394.670
3,Cardiff County Council,341100,NaN,NaN,NaN,NaN,3825.17,4442.687
4,Carmarthenshire County Council,180700,NaN,NaN,0.72,NaN,303.80,382.880
5,Ceredigion County Council,76900,NaN,NaN,NaN,NaN,NaN,NaN
6,City and County of Swansea,232500,NaN,NaN,72.24,NaN,1543.45,5905.470
7,Conwy CBC,110900,203.45,NaN,96.56,52.18,NaN,3391.650
8,Denbighshire County Council,96700,NaN,NaN,NaN,NaN,556.83,556.830
9,Flintshire County Council,149700,13.40,NaN,NaN,NaN,498.11,511.510
10,Gwynedd Council,119000,504.24,10.98,NaN,NaN,2305.79,3988.030
11,Isle of Anglesey CC,68600,NaN,NaN,NaN,NaN,NaN,NaN
12,Merthyr Tydfil CBC,55700,365.26,NaN,NaN,47.82,NaN,549.943
13,Monmouthshire CC,88100,NaN,NaN,NaN,NaN,NaN,NaN
14,Neath Port Talbot CBC,137400,634.00,NaN,NaN,18.00,NaN,1031.000
15,Newport City Council,141300,551.85,NaN,NaN,NaN,11.94,837.550
16,Pembrokeshire County Council,117100,155.75,NaN,NaN,NaN,NaN,924.000
17,Powys County Council,131300,NaN,NaN,NaN,NaN,NaN,21.101
18,Rhondda Cynon Taff CBC,234300,NaN,NaN,NaN,NaN,NaN,41.210
19,Torfaen CBC,90500,NaN,NaN,NaN,NaN,NaN,128.095
20,Vale of Glamorgan Council,125000,NaN,NaN,NaN,NaN,NaN,NaN
21,Wrexham CBC,133600,NaN,NaN,NaN,NaN,NaN,84.150

In [58]:
merge['Mixed glass per pop'] = merge['Mixed glass']/merge['Population']
merge['Mixed glass per pop'].mean()

0.0028245589217140879

In [69]:
(merge['Mixed glass']/merge['Population']).median()

0.00287002789376248

In [61]:
merge['New mixed glass'] = merge['Population']*0.0028245589217140879
merge[['Authority','Population','Mixed glass','New mixed glass']]

                         Authority Population  Mixed glass New mixed glass
0                Blaenau Gwent CBC      68400          NaN        193.1998
1                     Bridgend CBC     134600         3.72        380.1856
2                   Caerphilly CBC     173100          NaN        488.9311
3           Cardiff County Council     341100          NaN         963.457
4   Carmarthenshire County Council     180700          NaN        510.3978
5        Ceredigion County Council      76900          NaN        217.2086
6     City  and County of Swansea      232500          NaN        656.7099
7                        Conwy CBC     110900       203.45        313.2436
8      Denbighshire County Council      96700          NaN        273.1348
9        Flintshire County Council     149700        13.40        422.8365
10                 Gwynedd Council     119000       504.24        336.1225
11             Isle of Anglesey CC      68600          NaN        193.7647
12              Merthyr Tydfil CBC      55700       365.26        157.3279
13                Monmouthshire CC      88100          NaN        248.8436
14           Neath Port Talbot CBC     137400       634.00        388.0944
15            Newport City Council     141300       551.85        399.1102
16    Pembrokeshire County Council     117100       155.75        330.7558
17            Powys County Council     131300          NaN        370.8646
18          Rhondda Cynon Taff CBC     234300          NaN        661.7942
19                     Torfaen CBC      90500          NaN        255.6226
20       Vale of Glamorgan Council     125000          NaN        353.0699
21                     Wrexham CBC     133600          NaN        377.3611

In [62]:
sum(merge['New mixed glass'])

8492.036398133405

In [65]:
merge['combined'] = merge['Mixed glass'].replace(np.NaN, merge['New mixed glass'])
sum(merge['combined'])

8196.0298474341107

In [77]:
reload(massflow_baseline)

In [79]:
merge = massflow_baseline.get_pop().merge(massflow_baseline.get_com_rec_la(), how='left',on='Authority')
drs_list = ['Mixed glass','Mixed Plastic Bottles','Plastics','Mixed cans']
for drs in drs_list:
    merge['Estimated ' + drs] = merge['Population']*((merge[drs]/merge['Population']).median())
    #merge['New ' + drs] = merge[drs].replace(np.NaN, merge['Estimated ' +  drs])

In [81]:
(merge['Mixed cans']/merge['Population']).median()

0.00030075917168384124

In [80]:
merge

,Authority,Population,Mixed glass,Mixed Plastic Bottles,Plastics,Mixed cans,Estimated Mixed glass,New Mixed glass,Estimated Mixed Plastic Bottles,New Mixed Plastic Bottles,Estimated Plastics,New Plastics,Estimated Mixed cans,New Mixed cans
0,Blaenau Gwent CBC,68400,NaN,NaN,NaN,NaN,196.3099,196.309908,6.311193,6.311193,15.06516,15.065157,20.57193,20.571927
1,Bridgend CBC,134600,3.72,NaN,17.47,2.14,386.3058,3.720000,12.41939,12.419395,29.64576,17.470000,40.48218,2.140000
2,Caerphilly CBC,173100,NaN,NaN,NaN,NaN,496.8018,496.801828,15.97175,15.971748,38.12542,38.125418,52.06141,52.061413
3,Cardiff County Council,341100,NaN,NaN,NaN,NaN,978.9665,978.966515,31.47292,31.472924,75.12756,75.127557,102.589,102.588953
4,Carmarthenshire County Council,180700,NaN,NaN,0.72,NaN,518.614,518.614040,16.67299,16.672992,39.79932,0.720000,54.34718,54.347182
5,Ceredigion County Council,76900,NaN,NaN,NaN,NaN,220.7051,220.705145,7.095479,7.095479,16.93729,16.937289,23.12838,23.128380
6,City and County of Swansea,232500,NaN,NaN,72.24,NaN,667.2815,667.281485,21.45252,21.452521,51.20832,72.240000,69.92651,69.926507
7,Conwy CBC,110900,203.45,NaN,96.56,52.18,318.2861,203.450000,10.23262,10.232622,24.42582,96.560000,33.35419,52.180000
8,Denbighshire County Council,96700,NaN,NaN,NaN,NaN,277.5317,277.531697,8.922403,8.922403,21.29825,21.298255,29.08341,29.083412
9,Flintshire County Council,149700,13.40,NaN,NaN,NaN,429.6432,13.400000,13.81266,13.812655,32.97155,32.971549,45.02365,45.023648
10,Gwynedd Council,119000,504.24,10.98,NaN,NaN,341.5333,504.240000,10.98,10.980000,26.20985,26.209848,35.79034,35.790341
11,Isle of Anglesey CC,68600,NaN,NaN,NaN,NaN,196.8839,196.883914,6.329647,6.329647,15.10921,15.109207,20.63208,20.632079
12,Merthyr Tydfil CBC,55700,365.26,NaN,NaN,47.82,159.8606,365.260000,5.139378,5.139378,12.26797,12.267971,16.75229,47.820000
13,Monmouthshire CC,88100,NaN,NaN,NaN,NaN,252.8495,252.849457,8.128891,8.128891,19.4041,19.404098,26.49688,26.496883
14,Neath Port Talbot CBC,137400,634.00,NaN,NaN,18.00,394.3418,634.000000,12.67775,12.677748,30.26246,30.262464,41.32431,18.000000
15,Newport City Council,141300,551.85,NaN,NaN,NaN,405.5349,551.850000,13.0376,13.037597,31.12144,31.121442,42.49727,42.497271
16,Pembrokeshire County Council,117100,155.75,NaN,NaN,NaN,336.0803,155.750000,10.80469,10.804689,25.79137,25.791372,35.2189,35.218899
17,Powys County Council,131300,NaN,NaN,NaN,NaN,376.8347,376.834662,12.11491,12.114908,28.91893,28.918934,39.48968,39.489679
18,Rhondda Cynon Taff CBC,234300,NaN,NaN,NaN,NaN,672.4475,672.447536,21.61861,21.618605,51.60477,51.604769,70.46787,70.467874
19,Torfaen CBC,90500,NaN,NaN,NaN,NaN,259.7375,259.737524,8.350336,8.350336,19.9327,19.932700,27.21871,27.218705
20,Vale of Glamorgan Council,125000,NaN,NaN,NaN,NaN,358.7535,358.753487,11.53361,11.533613,27.53135,27.531353,37.5949,37.594896
21,Wrexham CBC,133600,NaN,NaN,NaN,NaN,383.4357,383.435727,12.32713,12.327126,29.42551,29.425510,40.18143,40.181425

In [92]:
com_rec_drs = massflow_baseline.get_com_rec_drs()
com_rec_drs

,Authority,DRS Glass Bottles,DRS Plastic Bottles,DRS Ferrous Cans,DRS Aluminium Cans,DRS Beverage Cartons
0,Blaenau Gwent CBC,147.232431,7.532578,16.457542,4.114385,NaN
1,Bridgend CBC,2.790000,8.735000,1.712000,0.428000,NaN
2,Caerphilly CBC,372.601371,19.062709,41.649130,10.412283,NaN
3,Cardiff County Council,734.224886,37.563779,82.071163,20.517791,NaN
4,Carmarthenshire County Council,388.960530,0.360000,43.477746,10.869436,NaN
5,Ceredigion County Council,165.528859,8.468644,18.502704,4.625676,NaN
6,City and County of Swansea,500.461114,36.120000,55.941206,13.985301,NaN
7,Conwy CBC,152.587500,48.280000,41.744000,10.436000,NaN
8,Denbighshire County Council,208.148773,10.649127,23.266730,5.816682,NaN
9,Flintshire County Council,10.050000,16.485774,36.018918,9.004730,NaN
10,Gwynedd Council,378.180000,10.980000,28.632273,7.158068,NaN
11,Isle of Anglesey CC,147.662935,7.554603,16.505663,4.126416,NaN
12,Merthyr Tydfil CBC,273.945000,6.133986,38.256000,9.564000,NaN
13,Monmouthshire CC,189.637093,9.702049,21.197506,5.299377,NaN
14,Neath Port Talbot CBC,475.500000,15.131232,14.400000,3.600000,NaN
15,Newport City Council,413.887500,15.560721,33.997817,8.499454,NaN
16,Pembrokeshire County Council,116.812500,12.895686,28.175119,7.043780,NaN
17,Powys County Council,282.625997,14.459467,31.591743,7.897936,NaN
18,Rhondda Cynon Taff CBC,504.335652,25.802384,56.374299,14.093575,NaN
19,Torfaen CBC,194.803143,9.966350,21.774964,5.443741,NaN
20,Vale of Glamorgan Council,269.065115,13.765677,30.075917,7.518979,NaN
21,Wrexham CBC,287.576795,14.712755,32.145140,8.036285,NaN

In [95]:
com_res_drs = massflow_baseline.get_com_res_drs()

In [96]:
com_res_drs[['Authority','DRS Beverage Cartons']]

                         Authority  DRS Beverage Cartons
0                Blaenau Gwent CBC              2.334892
1                     Bridgend CBC              8.696940
2                   Caerphilly CBC             14.044800
3           Cardiff County Council             30.979200
4   Carmarthenshire County Council              5.018496
5        Ceredigion County Council              4.657022
6     City  and County of Swansea              28.557648
7                        Conwy CBC              9.468788
8      Denbighshire County Council              1.880424
9        Flintshire County Council              8.438041
10                 Gwynedd Council             21.036848
11             Isle of Anglesey CC              4.154379
12              Merthyr Tydfil CBC              3.235260
13                Monmouthshire CC              5.335288
14           Neath Port Talbot CBC              7.504000
15            Newport City Council              8.002120
16    Pembrokeshire County Council              0.193088
17            Powys County Council             13.341451
18          Rhondda Cynon Taff CBC             14.189080
19                     Torfaen CBC              5.096112
20       Vale of Glamorgan Council              9.665376
21                     Wrexham CBC              9.979200

In [97]:
reload(massflow_baseline)

In [98]:
com_rec_drs = massflow_baseline.get_com_rec_drs()
com_rec_drs

,Authority,DRS Glass Bottles,DRS Plastic Bottles,DRS Ferrous Cans,DRS Aluminium Cans,DRS Beverage Cartons
0,Blaenau Gwent CBC,147.232431,7.532578,16.457542,4.114385,1.000668
1,Bridgend CBC,2.790000,8.735000,1.712000,0.428000,3.727260
2,Caerphilly CBC,372.601371,19.062709,41.649130,10.412283,6.019200
3,Cardiff County Council,734.224886,37.563779,82.071163,20.517791,13.276800
4,Carmarthenshire County Council,388.960530,0.360000,43.477746,10.869436,2.150784
5,Ceredigion County Council,165.528859,8.468644,18.502704,4.625676,1.995867
6,City and County of Swansea,500.461114,36.120000,55.941206,13.985301,12.238992
7,Conwy CBC,152.587500,48.280000,41.744000,10.436000,4.058052
8,Denbighshire County Council,208.148773,10.649127,23.266730,5.816682,0.805896
9,Flintshire County Council,10.050000,16.485774,36.018918,9.004730,3.616303
10,Gwynedd Council,378.180000,10.980000,28.632273,7.158068,9.015792
11,Isle of Anglesey CC,147.662935,7.554603,16.505663,4.126416,1.780448
12,Merthyr Tydfil CBC,273.945000,6.133986,38.256000,9.564000,1.386540
13,Monmouthshire CC,189.637093,9.702049,21.197506,5.299377,2.286552
14,Neath Port Talbot CBC,475.500000,15.131232,14.400000,3.600000,3.216000
15,Newport City Council,413.887500,15.560721,33.997817,8.499454,3.429480
16,Pembrokeshire County Council,116.812500,12.895686,28.175119,7.043780,0.082752
17,Powys County Council,282.625997,14.459467,31.591743,7.897936,5.717765
18,Rhondda Cynon Taff CBC,504.335652,25.802384,56.374299,14.093575,6.081034
19,Torfaen CBC,194.803143,9.966350,21.774964,5.443741,2.184048
20,Vale of Glamorgan Council,269.065115,13.765677,30.075917,7.518979,4.142304
21,Wrexham CBC,287.576795,14.712755,32.145140,8.036285,4.276800

In [100]:
com_res_drs

,Authority,DRS Glass Bottles,DRS Plastic Bottles,DRS Ferrous Cans,DRS Aluminium Cans,DRS Beverage Cartons
0,Blaenau Gwent CBC,18.012024,19.513026,5.670452,2.668448,2.334892
1,Bridgend CBC,67.090680,72.681570,21.121140,9.939360,8.696940
2,Caerphilly CBC,108.345600,117.374400,34.108800,16.051200,14.044800
3,Cardiff County Council,238.982400,258.897600,75.235200,35.404800,30.979200
4,Carmarthenshire County Council,38.714112,41.940288,12.187776,5.735424,5.018496
5,Ceredigion County Council,35.925599,38.919399,11.309911,5.322311,4.657022
6,City and County of Swansea,220.301856,238.660344,69.354288,32.637312,28.557648
7,Conwy CBC,73.044936,79.132014,22.995628,10.821472,9.468788
8,Denbighshire County Council,14.506128,15.714972,4.566744,2.149056,1.880424
9,Flintshire County Council,65.093458,70.517912,20.492385,9.643475,8.438041
10,Gwynedd Council,162.284256,175.807944,51.089488,24.042112,21.036848
11,Isle of Anglesey CC,32.048064,34.718736,10.089205,4.747861,4.154379
12,Merthyr Tydfil CBC,24.957720,27.037530,7.857060,3.697440,3.235260
13,Monmouthshire CC,41.157936,44.587764,12.957128,6.097472,5.335288
14,Neath Port Talbot CBC,57.888000,62.712000,18.224000,8.576000,7.504000
15,Newport City Council,61.730640,66.874860,19.433720,9.145280,8.002120
16,Pembrokeshire County Council,1.489536,1.613664,0.468928,0.220672,0.193088
17,Powys County Council,102.919766,111.496414,32.400667,15.247373,13.341451
18,Rhondda Cynon Taff CBC,109.458620,118.580171,34.459195,16.216092,14.189080
19,Torfaen CBC,39.312864,42.588936,12.376272,5.824128,5.096112
20,Vale of Glamorgan Council,74.561472,80.774928,23.473056,11.046144,9.665376
21,Wrexham CBC,76.982400,83.397600,24.235200,11.404800,9.979200

In [107]:
test_com_rec_drs = pd.DataFrame(columns=['Authority','DRS Glass Bottles',
                                        'DRS Plastic Bottles','DRS Ferrous Cans',
                                        'DRS Aluminium Cans','DRS Beverage Cartons'])
test_com_rec_drs['Authority'] = com_res_drs['Authority']
test_com_rec_drs['DRS Glass Bottles'] = com_res_drs['DRS Glass Bottles']*(.6/.4)
test_com_rec_drs['DRS Plastic Bottles'] = com_res_drs['DRS Plastic Bottles']*(.3/.7)
test_com_rec_drs['DRS Ferrous Cans'] = com_res_drs['DRS Ferrous Cans']*(.4/.6)
test_com_rec_drs['DRS Aluminium Cans'] = com_res_drs['DRS Aluminium Cans']*(.4/.6)
test_com_rec_drs['DRS Beverage Cartons'] = com_res_drs['DRS Beverage Cartons']*(.3/.7)
test_com_rec_drs

,Authority,DRS Glass Bottles,DRS Plastic Bottles,DRS Ferrous Cans,DRS Aluminium Cans,DRS Beverage Cartons
0,Blaenau Gwent CBC,27.018036,8.362725,3.780301,1.778965,1.000668
1,Bridgend CBC,100.636020,31.149244,14.080760,6.626240,3.727260
2,Caerphilly CBC,162.518400,50.303314,22.739200,10.700800,6.019200
3,Cardiff County Council,358.473600,110.956114,50.156800,23.603200,13.276800
4,Carmarthenshire County Council,58.071168,17.974409,8.125184,3.823616,2.150784
5,Ceredigion County Council,53.888399,16.679742,7.539941,3.548207,1.995867
6,City and County of Swansea,330.452784,102.283005,46.236192,21.758208,12.238992
7,Conwy CBC,109.567404,33.913720,15.330419,7.214315,4.058052
8,Denbighshire County Council,21.759192,6.734988,3.044496,1.432704,0.805896
9,Flintshire County Council,97.640186,30.221962,13.661590,6.428983,3.616303
10,Gwynedd Council,243.426384,75.346262,34.059659,16.028075,9.015792
11,Isle of Anglesey CC,48.072096,14.879458,6.726137,3.165241,1.780448
12,Merthyr Tydfil CBC,37.436580,11.587513,5.238040,2.464960,1.386540
13,Monmouthshire CC,61.736904,19.109042,8.638085,4.064981,2.286552
14,Neath Port Talbot CBC,86.832000,26.876571,12.149333,5.717333,3.216000
15,Newport City Council,92.595960,28.660654,12.955813,6.096853,3.429480
16,Pembrokeshire County Council,2.234304,0.691570,0.312619,0.147115,0.082752
17,Powys County Council,154.379650,47.784177,21.600445,10.164915,5.717765
18,Rhondda Cynon Taff CBC,164.187930,50.820073,22.972797,10.810728,6.081034
19,Torfaen CBC,58.969296,18.252401,8.250848,3.882752,2.184048
20,Vale of Glamorgan Council,111.842208,34.617826,15.648704,7.364096,4.142304
21,Wrexham CBC,115.473600,35.741829,16.156800,7.603200,4.276800

In [111]:
test_com_rec_sum = (test_com_rec_drs.sum(axis=0, numeric_only=True).div(1000).to_frame()
                     .reset_index().rename(columns={'index': 'DRS Materials',0: 'Commercial recycling'}))
test_com_rec_sum

          DRS Materials  Commercial recycling
0     DRS Glass Bottles              2.497212
1   DRS Plastic Bottles              0.772947
2      DRS Ferrous Cans              0.349404
3    DRS Aluminium Cans              0.164425
4  DRS Beverage Cartons              0.092489

In [112]:
reload(massflow_baseline)

In [113]:
baseline = massflow_baseline.get_massflow_baseline()
baseline

,DRS Materials,Total Mass in Thousand Tonnes,Household Kerbside Recycling,Household Kerbside Residual,HWRCs Recycling,HWRCs Residual,Commercial Recycling,Commercial Residual,Remains in Environment
0,DRS Glass Bottles,95.370,47.312957,8.839449,7.643751,1.132976,6.216617,1.664808,0.95370
1,DRS Plastic Bottles,22.542,20.048890,6.542926,1.653019,0.641032,0.349923,1.803542,0.22542
2,DRS Ferrous Cans,2.890,2.485369,0.673358,0.250098,0.177158,0.713968,0.524106,0.02890
3,DRS Aluminium Cans,5.202,4.097704,1.410412,0.135646,0.240873,0.178492,0.246638,0.05202
4,DRS Beverage Cartons,2.890,0.748891,1.603233,0.036783,0.067988,0.092489,0.215808,0.02890
5,Total,128.316,74.693810,19.069379,9.719297,2.260028,7.551489,4.454903,1.28316

#Commercial residual waste

In [9]:
com_res = (raw[(raw.QuestionNumber == 'Q023') & (raw.ColText == 'Tonnage')]
             .pivot_table(values='Data', index=['Authority','Period'],
                          columns='RowText', aggfunc = lambda x: x)
             .reset_index())
com_res.columns

Index([                                                  u'Authority',
                                                            u'Period',
                               u'Asbestos Waste separately collected',
                                                   u'Beach cleansing',
                             u'Civic amenity sites waste : Household',
                         u'Civic amenity sites waste : Non Household',
                                         u'Collected gully emptyings',
                           u'Collected household waste : Bulky Waste',
                                 u'Collected household waste : Other',
                    u'Collected household waste : Regular Collection',
                       u'Collected household waste : Street Cleaning',
           u'Collected non-household waste : Commercial & Industrial',
       u'Collected non-household waste : Construction and Demolition',
                     u'Collected non-household waste : Grounds Waste',
                    u'Collected non-household waste : Highways waste',
                             u'Collected non-household waste : Other',
                                             u'Other collected waste',
                             u'Separately collected healthcare waste',
              u'Waste Arising from clearance of fly-tipped materials'],
      dtype='object', name=u'RowText')

In [10]:
com_res_qtr = com_res[['Authority','Period','Collected non-household waste : Commercial & Industrial']]

In [11]:
com_res_qtr

RowText,Authority,Period,Collected non-household waste : Commercial & Industrial
0,Blaenau Gwent CBC,Apr 14 - Jun 14,251.770
1,Blaenau Gwent CBC,Jan 15 - Mar 15,194.440
2,Blaenau Gwent CBC,Jul 14 - Sep 14,193.840
3,Blaenau Gwent CBC,Oct 14 - Dec 14,193.840
4,Bridgend CBC,Apr 14 - Jun 14,736.040
5,Bridgend CBC,Jan 15 - Mar 15,779.770
6,Bridgend CBC,Jul 14 - Sep 14,784.580
7,Bridgend CBC,Oct 14 - Dec 14,805.660
8,Caerphilly CBC,Apr 14 - Jun 14,1209.000
9,Caerphilly CBC,Jan 15 - Mar 15,1269.000
10,Caerphilly CBC,Jul 14 - Sep 14,1269.000
11,Caerphilly CBC,Oct 14 - Dec 14,1269.000
12,Cardiff County Council,Apr 14 - Jun 14,2553.460
13,Cardiff County Council,Jan 15 - Mar 15,2990.710
14,Cardiff County Council,Jul 14 - Sep 14,2472.250
15,Cardiff County Council,Oct 14 - Dec 14,3047.580
16,Carmarthenshire County Council,Apr 14 - Jun 14,546.240
17,Carmarthenshire County Council,Jan 15 - Mar 15,569.780
18,Carmarthenshire County Council,Jul 14 - Sep 14,503.360
19,Carmarthenshire County Council,Oct 14 - Dec 14,172.940
20,Ceredigion County Council,Apr 14 - Jun 14,NaN
21,Ceredigion County Council,Jan 15 - Mar 15,NaN
22,Ceredigion County Council,Jul 14 - Sep 14,NaN
23,Ceredigion County Council,Oct 14 - Dec 14,NaN
24,City and County of Swansea,Apr 14 - Jun 14,2514.600
25,City and County of Swansea,Jan 15 - Mar 15,2432.060
26,City and County of Swansea,Jul 14 - Sep 14,2599.620
27,City and County of Swansea,Oct 14 - Dec 14,2652.880
28,Conwy CBC,Apr 14 - Jun 14,952.090
29,Conwy CBC,Jan 15 - Mar 15,733.720
30,Conwy CBC,Jul 14 - Sep 14,741.580
31,Conwy CBC,Oct 14 - Dec 14,954.320
32,Denbighshire County Council,Apr 14 - Jun 14,142.980
33,Denbighshire County Council,Jan 15 - Mar 15,195.270
34,Denbighshire County Council,Jul 14 - Sep 14,151.150
35,Denbighshire County Council,Oct 14 - Dec 14,182.180
36,Flintshire County Council,Apr 14 - Jun 14,810.330
37,Flintshire County Council,Jan 15 - Mar 15,677.566
38,Flintshire County Council,Jul 14 - Sep 14,773.990
39,Flintshire County Council,Oct 14 - Dec 14,751.700
40,Gwynedd Council,Apr 14 - Jun 14,2078.640
41,Gwynedd Council,Jan 15 - Mar 15,1444.440
42,Gwynedd Council,Jul 14 - Sep 14,2390.040
43,Gwynedd Council,Oct 14 - Dec 14,1600.040
44,Isle of Anglesey CC,Apr 14 - Jun 14,NaN
45,Isle of Anglesey CC,Jan 15 - Mar 15,NaN
46,Isle of Anglesey CC,Jul 14 - Sep 14,NaN
47,Isle of Anglesey CC,Oct 14 - Dec 14,NaN
48,Merthyr Tydfil CBC,Apr 14 - Jun 14,180.640
49,Merthyr Tydfil CBC,Jan 15 - Mar 15,NaN
50,Merthyr Tydfil CBC,Jul 14 - Sep 14,173.820
51,Merthyr Tydfil CBC,Oct 14 - Dec 14,800.990
52,Monmouthshire CC,Apr 14 - Jun 14,493.040
53,Monmouthshire CC,Jan 15 - Mar 15,449.040
54,Monmouthshire CC,Jul 14 - Sep 14,505.100
55,Monmouthshire CC,Oct 14 - Dec 14,458.280
56,Neath Port Talbot CBC,Apr 14 - Jun 14,670.000
57,Neath Port Talbot CBC,Jan 15 - Mar 15,670.000
58,Neath Port Talbot CBC,Jul 14 - Sep 14,670.000
59,Neath Port Talbot CBC,Oct 14 - Dec 14,670.000
60,Newport City Council,Apr 14 - Jun 14,667.300
61,Newport City Council,Jan 15 - Mar 15,733.760
62,Newport City Council,Jul 14 - Sep 14,706.100
63,Newport City Council,Oct 14 - Dec 14,750.740
64,Pembrokeshire County Council,Apr 14 - Jun 14,29.110
65,Pembrokeshire County Council,Jan 15 - Mar 15,NaN
66,Pembrokeshire County Council,Jul 14 - Sep 14,NaN
67,Pembrokeshire County Council,Oct 14 - Dec 14,39.850
68,Powys County Council,Apr 14 - Jun 14,1275.228
69,Powys County Council,Jan 15 - Mar 15,1082.504
70,Powys County Council,Jul 14 - Sep 14,1246.932
71,Powys County Council,Oct 14 - Dec 14,1160.140
72,Rhondda Cynon Taff CBC,Apr 14 - Jun 14,NaN
73,Rhondda Cynon Taff CBC,Jan 15 - Mar 15,NaN
74,Rhondda Cynon Taff CBC,Jul 14 - Sep 14,NaN
75,Rhondda Cynon Taff CBC,Oct 14 - Dec 14,NaN
76,Torfaen CBC,Apr 14 - Jun 14,455.010
77,Torfaen CBC,Jan 15 - Mar 15,455.010
78,Torfaen CBC,Jul 14 - Sep 14,455.010
79,Torfaen CBC,Oct 14 - Dec 14,455.010
80,Vale of Glamorgan Council,Apr 14 - Jun 14,867.680
81,Vale of Glamorgan Council,Jan 15 - Mar 15,851.230
82,Vale of Glamorgan Council,Jul 14 - Sep 14,865.050
83,Vale of Glamorgan Council,Oct 14 - Dec 14,867.960
84,Wrexham CBC,Apr 14 - Jun 14,891.000
85,Wrexham CBC,Jan 15 - Mar 15,891.000
86,Wrexham CBC,Jul 14 - Sep 14,891.000
87,Wrexham CBC,Oct 14 - Dec 14,891.000

In [12]:
com_res_la = com_res_qtr.groupby('Authority').agg(np.sum).reset_index()

In [82]:
com_res_la = pop_la.merge(com_res_la, how='left', on='Authority')
com_res_la

,Authority,Population,Collected non-household waste : Commercial & Industrial
0,Blaenau Gwent CBC,68400,833.890
1,Bridgend CBC,134600,3106.050
2,Caerphilly CBC,173100,5016.000
3,Cardiff County Council,341100,11064.000
4,Carmarthenshire County Council,180700,1792.320
5,Ceredigion County Council,76900,NaN
6,City and County of Swansea,232500,10199.160
7,Conwy CBC,110900,3381.710
8,Denbighshire County Council,96700,671.580
9,Flintshire County Council,149700,3013.586
10,Gwynedd Council,119000,7513.160
11,Isle of Anglesey CC,68600,NaN
12,Merthyr Tydfil CBC,55700,1155.450
13,Monmouthshire CC,88100,1905.460
14,Neath Port Talbot CBC,137400,2680.000
15,Newport City Council,141300,2857.900
16,Pembrokeshire County Council,117100,68.960
17,Powys County Council,131300,4764.804
18,Rhondda Cynon Taff CBC,234300,NaN
19,Torfaen CBC,90500,1820.040
20,Vale of Glamorgan Council,125000,3451.920
21,Wrexham CBC,133600,3564.000

In [13]:
com_res_drs = pd.DataFrame(columns=['Authority','DRS Glass Bottles',
                                    'DRS Plastic Bottles','DRS Ferrous Cans',
                                    'DRS Aluminium Cans','DRS Beverage Cartons'])
com_res_drs['Authority'] = com_res_la['Authority']
com_res_drs['DRS Glass Bottles'] = com_res_la['Collected non-household waste : Commercial & Industrial']*0.0216
com_res_drs['DRS Plastic Bottles'] = com_res_la['Collected non-household waste : Commercial & Industrial']*0.0234
com_res_drs['DRS Ferrous Cans'] = com_res_la['Collected non-household waste : Commercial & Industrial']*0.0068
com_res_drs['DRS Aluminium Cans'] = com_res_la['Collected non-household waste : Commercial & Industrial']*0.0032
com_res_drs['DRS Beverage Cartons'] = com_res_la['Collected non-household waste : Commercial & Industrial']*0.0028

In [14]:
com_res_drs

,Authority,DRS Glass Bottles,DRS Plastic Bottles,DRS Ferrous Cans,DRS Aluminium Cans,DRS Beverage Cartons
0,Blaenau Gwent CBC,18.012024,19.513026,5.670452,2.668448,2.334892
1,Bridgend CBC,67.090680,72.681570,21.121140,9.939360,8.696940
2,Caerphilly CBC,108.345600,117.374400,34.108800,16.051200,14.044800
3,Cardiff County Council,238.982400,258.897600,75.235200,35.404800,30.979200
4,Carmarthenshire County Council,38.714112,41.940288,12.187776,5.735424,5.018496
5,Ceredigion County Council,NaN,NaN,NaN,NaN,NaN
6,City and County of Swansea,220.301856,238.660344,69.354288,32.637312,28.557648
7,Conwy CBC,73.044936,79.132014,22.995628,10.821472,9.468788
8,Denbighshire County Council,14.506128,15.714972,4.566744,2.149056,1.880424
9,Flintshire County Council,65.093458,70.517912,20.492385,9.643475,8.438041
10,Gwynedd Council,162.284256,175.807944,51.089488,24.042112,21.036848
11,Isle of Anglesey CC,NaN,NaN,NaN,NaN,NaN
12,Merthyr Tydfil CBC,24.957720,27.037530,7.857060,3.697440,3.235260
13,Monmouthshire CC,41.157936,44.587764,12.957128,6.097472,5.335288
14,Neath Port Talbot CBC,57.888000,62.712000,18.224000,8.576000,7.504000
15,Newport City Council,61.730640,66.874860,19.433720,9.145280,8.002120
16,Pembrokeshire County Council,1.489536,1.613664,0.468928,0.220672,0.193088
17,Powys County Council,102.919766,111.496414,32.400667,15.247373,13.341451
18,Rhondda Cynon Taff CBC,NaN,NaN,NaN,NaN,NaN
19,Torfaen CBC,39.312864,42.588936,12.376272,5.824128,5.096112
20,Vale of Glamorgan Council,74.561472,80.774928,23.473056,11.046144,9.665376
21,Wrexham CBC,76.982400,83.397600,24.235200,11.404800,9.979200

In [88]:
reload(massflow_baseline)

In [87]:
massflow_baseline.get_com_res_drs()

,Authority,DRS Glass Bottles,DRS Plastic Bottles,DRS Ferrous Cans,DRS Aluminium Cans,DRS Beverage Cartons
0,Blaenau Gwent CBC,18.012024,19.513026,5.670452,2.668448,2.334892
1,Bridgend CBC,67.090680,72.681570,21.121140,9.939360,8.696940
2,Caerphilly CBC,108.345600,117.374400,34.108800,16.051200,14.044800
3,Cardiff County Council,238.982400,258.897600,75.235200,35.404800,30.979200
4,Carmarthenshire County Council,38.714112,41.940288,12.187776,5.735424,5.018496
5,Ceredigion County Council,35.925599,38.919399,11.309911,5.322311,4.657022
6,City and County of Swansea,220.301856,238.660344,69.354288,32.637312,28.557648
7,Conwy CBC,73.044936,79.132014,22.995628,10.821472,9.468788
8,Denbighshire County Council,14.506128,15.714972,4.566744,2.149056,1.880424
9,Flintshire County Council,65.093458,70.517912,20.492385,9.643475,8.438041
10,Gwynedd Council,162.284256,175.807944,51.089488,24.042112,21.036848
11,Isle of Anglesey CC,32.048064,34.718736,10.089205,4.747861,4.154379
12,Merthyr Tydfil CBC,24.957720,27.037530,7.857060,3.697440,3.235260
13,Monmouthshire CC,41.157936,44.587764,12.957128,6.097472,5.335288
14,Neath Port Talbot CBC,57.888000,62.712000,18.224000,8.576000,7.504000
15,Newport City Council,61.730640,66.874860,19.433720,9.145280,8.002120
16,Pembrokeshire County Council,1.489536,1.613664,0.468928,0.220672,0.193088
17,Powys County Council,102.919766,111.496414,32.400667,15.247373,13.341451
18,Rhondda Cynon Taff CBC,109.458620,118.580171,34.459195,16.216092,14.189080
19,Torfaen CBC,39.312864,42.588936,12.376272,5.824128,5.096112
20,Vale of Glamorgan Council,74.561472,80.774928,23.473056,11.046144,9.665376
21,Wrexham CBC,76.982400,83.397600,24.235200,11.404800,9.979200

In [90]:
massflow_baseline.get_massflow_baseline()

,DRS Materials,Total Mass in Thousand Tonnes,Household Kerbside Recycling,Household Kerbside Residual,HWRCs Recycling,HWRCs Residual,Commercial Residual,Remains in Environment
0,DRS Glass Bottles,95.370,47.312957,8.839449,7.643751,1.132976,1.664808,0.95370
1,DRS Plastic Bottles,22.542,20.048890,6.542926,1.653019,0.641032,1.803542,0.22542
2,DRS Ferrous Cans,2.890,2.485369,0.673358,0.250098,0.177158,0.524106,0.02890
3,DRS Aluminium Cans,5.202,4.097704,1.410412,0.135646,0.240873,0.246638,0.05202
4,DRS Beverage Cartons,2.890,0.748891,1.603233,0.036783,0.067988,0.215808,0.02890
5,Total,128.316,74.693810,19.069379,9.719297,2.260028,4.454903,1.28316

In [16]:
#From before the interpolation
com_res_sum

                      Commercial Residual
DRS Glass Bottles                1.487376
DRS Plastic Bottles              1.611324
DRS Ferrous Cans                 0.468248
DRS Aluminium Cans               0.220352
DRS Beverage Cartons             0.192808

DRS Glass Bottles is really low compared to Scotland's numbers ... 20 thousand tonnes instead of 1.48