In [1]:
import numpy as np 
import pandas as pd 
import os.path as op  
import datetime as dt 
import time 

# The default data directory will be '../../data' 
# This can be redefined by the user of the function. 
data_dir = op.join('data') 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
import massflow_baseline

In [3]:
raw = massflow_baseline.get_data()

Litter = Street Cleaning - Flytipping - Mechanical Sweeping not recycled - Bin Litter.
And 100% of these cateogories are DRS materials

In [4]:
pd.crosstab([raw['QuText'], raw['QuestionNumber']], raw['ColText'])

,ColText,% recycled by dismantler,Collected Co-mingled?,Destination of residual,No of segregated litter bins by material type,No. of LA bring sites by material type,No. of households receiving a collection,Number,Percentage weighed,Proportion of which construction & demolition waste,Tonnage,Tonnage Collected for Reuse,Tonnage Collected for recycling,Tonnage Collected for reuse but actually rejected / disposed,Tonnage collected for recycling,Tonnage collected for recycling but actually rejected / disposed,Tonnage collected for recycling but actually rejected/disposed,Tonnage collected for reuse,Tonnage collected for reuse but actually rejected / disposed,Tonnage collected for reuse but actually rejected/disposed,Tonnage from household Sources
QuText,QuestionNumber,,,,,,,,,,,,,,,,,,,,
Composting / Recycling tonnage collected through any other recycling schemes. Please note that it is optional to report how much of the total tonnage is from household sources - please see Help for further information.,Q018,0,0,0,0,0,0,0,0,0,51,0,0,0,0,0,0,0,0,0,8
How many abandoned vehicles were disposed of by your authority and what percentage was recycled?,Q025,29,0,0,0,0,0,40,0,0,31,0,0,0,0,0,0,0,0,0,0
Please provide details of other waste collected for disposal. (The destination of the residual is required for authorities in Wales only.),Q023,0,0,642,0,0,0,0,568,19,647,0,0,0,0,0,0,0,0,0,0
"Tonnes of material collected from commercial, industrial or other non household sources by LA or its contractors",Q011,0,198,0,0,0,0,0,0,0,0,16,0,12,293,0,29,0,0,0,0
Tonnes of material collected through kerbside schemes by non contracted voluntary/community sector from household sources,Q012,0,52,0,0,0,0,0,0,0,0,112,0,6,30,0,1,0,0,0,0
Tonnes of material collected at bring sites operated by LA or its contractors,Q017,0,0,0,0,124,0,0,0,0,0,0,0,0,341,52,0,109,40,0,0
Tonnes of material collected for recycling at street recycling bins,Q034,0,0,0,1,0,0,0,0,0,0,0,0,0,5,0,1,1,0,1,0
Tonnes of material collected for recycling/reuse at CA Sites operated by LA or its contractors,Q016,0,0,0,0,0,0,0,0,0,0,0,0,0,1910,248,0,334,158,0,0
Tonnes of material collected through kerbside schemes from household sources by LA or its contractors,Q010,0,414,0,0,0,352,0,0,0,0,41,0,11,534,0,31,0,0,0,0
Tonnes of materials collected at bring sites operated by voluntary / community sector,Q033,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,10,0,0,0

In [5]:
res = (raw[(raw.QuestionNumber == 'Q023') & (raw.ColText == 'Tonnage')]
             .pivot_table(values='Data', index=['Authority','Period'],
                          columns='RowText', aggfunc = lambda x: x)
             .reset_index())
res.columns

Index([                                                  u'Authority',
                                                            u'Period',
                               u'Asbestos Waste separately collected',
                                                   u'Beach cleansing',
                             u'Civic amenity sites waste : Household',
                         u'Civic amenity sites waste : Non Household',
                                         u'Collected gully emptyings',
                           u'Collected household waste : Bulky Waste',
                                 u'Collected household waste : Other',
                    u'Collected household waste : Regular Collection',
                       u'Collected household waste : Street Cleaning',
           u'Collected non-household waste : Commercial & Industrial',
       u'Collected non-household waste : Construction and Demolition',
                     u'Collected non-household waste : Grounds Waste',
                    u'Collected non-household waste : Highways waste',
                             u'Collected non-household waste : Other',
                                             u'Other collected waste',
                             u'Separately collected healthcare waste',
              u'Waste Arising from clearance of fly-tipped materials'],
      dtype='object', name=u'RowText')

In [6]:
pub_res_qtr = res[['Authority','Period','Collected household waste : Street Cleaning']]
#Only Merthyr did not have any data

In [7]:
pub_res_qtr

RowText,Authority,Period,Collected household waste : Street Cleaning
0,Blaenau Gwent CBC,Apr 14 - Jun 14,110.920
1,Blaenau Gwent CBC,Jan 15 - Mar 15,110.490
2,Blaenau Gwent CBC,Jul 14 - Sep 14,77.010
3,Blaenau Gwent CBC,Oct 14 - Dec 14,99.190
4,Bridgend CBC,Apr 14 - Jun 14,1086.780
5,Bridgend CBC,Jan 15 - Mar 15,443.700
6,Bridgend CBC,Jul 14 - Sep 14,1139.280
7,Bridgend CBC,Oct 14 - Dec 14,727.720
8,Caerphilly CBC,Apr 14 - Jun 14,74.660
9,Caerphilly CBC,Jan 15 - Mar 15,783.720
10,Caerphilly CBC,Jul 14 - Sep 14,559.720
11,Caerphilly CBC,Oct 14 - Dec 14,779.660
12,Cardiff County Council,Apr 14 - Jun 14,1464.510
13,Cardiff County Council,Jan 15 - Mar 15,1461.330
14,Cardiff County Council,Jul 14 - Sep 14,1403.840
15,Cardiff County Council,Oct 14 - Dec 14,1810.140
16,Carmarthenshire County Council,Apr 14 - Jun 14,91.520
17,Carmarthenshire County Council,Jan 15 - Mar 15,154.200
18,Carmarthenshire County Council,Jul 14 - Sep 14,144.980
19,Carmarthenshire County Council,Oct 14 - Dec 14,50.100
20,Ceredigion County Council,Apr 14 - Jun 14,863.290
21,Ceredigion County Council,Jan 15 - Mar 15,1840.820
22,Ceredigion County Council,Jul 14 - Sep 14,278.300
23,Ceredigion County Council,Oct 14 - Dec 14,940.450
24,City and County of Swansea,Apr 14 - Jun 14,862.740
25,City and County of Swansea,Jan 15 - Mar 15,848.540
26,City and County of Swansea,Jul 14 - Sep 14,804.540
27,City and County of Swansea,Oct 14 - Dec 14,1224.880
28,Conwy CBC,Apr 14 - Jun 14,827.690
29,Conwy CBC,Jan 15 - Mar 15,842.160
30,Conwy CBC,Jul 14 - Sep 14,558.980
31,Conwy CBC,Oct 14 - Dec 14,762.850
32,Denbighshire County Council,Apr 14 - Jun 14,63.390
33,Denbighshire County Council,Jan 15 - Mar 15,51.820
34,Denbighshire County Council,Jul 14 - Sep 14,65.840
35,Denbighshire County Council,Oct 14 - Dec 14,56.840
36,Flintshire County Council,Apr 14 - Jun 14,133.230
37,Flintshire County Council,Jan 15 - Mar 15,95.966
38,Flintshire County Council,Jul 14 - Sep 14,100.800
39,Flintshire County Council,Oct 14 - Dec 14,97.900
40,Gwynedd Council,Apr 14 - Jun 14,1125.030
41,Gwynedd Council,Jan 15 - Mar 15,773.240
42,Gwynedd Council,Jul 14 - Sep 14,997.200
43,Gwynedd Council,Oct 14 - Dec 14,600.650
44,Isle of Anglesey CC,Apr 14 - Jun 14,830.740
45,Isle of Anglesey CC,Jan 15 - Mar 15,692.100
46,Isle of Anglesey CC,Jul 14 - Sep 14,756.860
47,Isle of Anglesey CC,Oct 14 - Dec 14,575.300
48,Merthyr Tydfil CBC,Apr 14 - Jun 14,NaN
49,Merthyr Tydfil CBC,Jan 15 - Mar 15,NaN
50,Merthyr Tydfil CBC,Jul 14 - Sep 14,NaN
51,Merthyr Tydfil CBC,Oct 14 - Dec 14,NaN
52,Monmouthshire CC,Apr 14 - Jun 14,177.270
53,Monmouthshire CC,Jan 15 - Mar 15,175.710
54,Monmouthshire CC,Jul 14 - Sep 14,199.860
55,Monmouthshire CC,Oct 14 - Dec 14,270.600
56,Neath Port Talbot CBC,Apr 14 - Jun 14,492.000
57,Neath Port Talbot CBC,Jan 15 - Mar 15,527.000
58,Neath Port Talbot CBC,Jul 14 - Sep 14,452.000
59,Neath Port Talbot CBC,Oct 14 - Dec 14,629.000
60,Newport City Council,Apr 14 - Jun 14,321.960
61,Newport City Council,Jan 15 - Mar 15,650.930
62,Newport City Council,Jul 14 - Sep 14,416.740
63,Newport City Council,Oct 14 - Dec 14,571.370
64,Pembrokeshire County Council,Apr 14 - Jun 14,378.530
65,Pembrokeshire County Council,Jan 15 - Mar 15,282.610
66,Pembrokeshire County Council,Jul 14 - Sep 14,420.400
67,Pembrokeshire County Council,Oct 14 - Dec 14,305.210
68,Powys County Council,Apr 14 - Jun 14,141.600
69,Powys County Council,Jan 15 - Mar 15,154.560
70,Powys County Council,Jul 14 - Sep 14,78.160
71,Powys County Council,Oct 14 - Dec 14,135.400
72,Rhondda Cynon Taff CBC,Apr 14 - Jun 14,911.320
73,Rhondda Cynon Taff CBC,Jan 15 - Mar 15,513.180
74,Rhondda Cynon Taff CBC,Jul 14 - Sep 14,713.880
75,Rhondda Cynon Taff CBC,Oct 14 - Dec 14,490.700
76,Torfaen CBC,Apr 14 - Jun 14,33.340
77,Torfaen CBC,Jan 15 - Mar 15,39.230
78,Torfaen CBC,Jul 14 - Sep 14,32.160
79,Torfaen CBC,Oct 14 - Dec 14,29.280
80,Vale of Glamorgan Council,Apr 14 - Jun 14,603.040
81,Vale of Glamorgan Council,Jan 15 - Mar 15,428.940
82,Vale of Glamorgan Council,Jul 14 - Sep 14,553.500
83,Vale of Glamorgan Council,Oct 14 - Dec 14,750.560
84,Wrexham CBC,Apr 14 - Jun 14,606.520
85,Wrexham CBC,Jan 15 - Mar 15,381.640
86,Wrexham CBC,Jul 14 - Sep 14,341.300
87,Wrexham CBC,Oct 14 - Dec 14,711.960

In [9]:
pub_fly_qtr = res[['Authority','Period','Waste Arising from clearance of fly-tipped materials']]
pub_fly_qtr
#not all LAs have this category, but Merthyr does...

RowText,Authority,Period,Waste Arising from clearance of fly-tipped materials
0,Blaenau Gwent CBC,Apr 14 - Jun 14,NaN
1,Blaenau Gwent CBC,Jan 15 - Mar 15,NaN
2,Blaenau Gwent CBC,Jul 14 - Sep 14,NaN
3,Blaenau Gwent CBC,Oct 14 - Dec 14,NaN
4,Bridgend CBC,Apr 14 - Jun 14,NaN
5,Bridgend CBC,Jan 15 - Mar 15,NaN
6,Bridgend CBC,Jul 14 - Sep 14,NaN
7,Bridgend CBC,Oct 14 - Dec 14,NaN
8,Caerphilly CBC,Apr 14 - Jun 14,NaN
9,Caerphilly CBC,Jan 15 - Mar 15,NaN
10,Caerphilly CBC,Jul 14 - Sep 14,NaN
11,Caerphilly CBC,Oct 14 - Dec 14,NaN
12,Cardiff County Council,Apr 14 - Jun 14,333.180
13,Cardiff County Council,Jan 15 - Mar 15,199.180
14,Cardiff County Council,Jul 14 - Sep 14,306.760
15,Cardiff County Council,Oct 14 - Dec 14,320.440
16,Carmarthenshire County Council,Apr 14 - Jun 14,NaN
17,Carmarthenshire County Council,Jan 15 - Mar 15,24.700
18,Carmarthenshire County Council,Jul 14 - Sep 14,7.280
19,Carmarthenshire County Council,Oct 14 - Dec 14,5.080
20,Ceredigion County Council,Apr 14 - Jun 14,0.520
21,Ceredigion County Council,Jan 15 - Mar 15,NaN
22,Ceredigion County Council,Jul 14 - Sep 14,NaN
23,Ceredigion County Council,Oct 14 - Dec 14,NaN
24,City and County of Swansea,Apr 14 - Jun 14,NaN
25,City and County of Swansea,Jan 15 - Mar 15,NaN
26,City and County of Swansea,Jul 14 - Sep 14,NaN
27,City and County of Swansea,Oct 14 - Dec 14,NaN
28,Conwy CBC,Apr 14 - Jun 14,NaN
29,Conwy CBC,Jan 15 - Mar 15,NaN
30,Conwy CBC,Jul 14 - Sep 14,NaN
31,Conwy CBC,Oct 14 - Dec 14,NaN
32,Denbighshire County Council,Apr 14 - Jun 14,NaN
33,Denbighshire County Council,Jan 15 - Mar 15,NaN
34,Denbighshire County Council,Jul 14 - Sep 14,NaN
35,Denbighshire County Council,Oct 14 - Dec 14,NaN
36,Flintshire County Council,Apr 14 - Jun 14,25.660
37,Flintshire County Council,Jan 15 - Mar 15,21.458
38,Flintshire County Council,Jul 14 - Sep 14,24.510
39,Flintshire County Council,Oct 14 - Dec 14,23.810
40,Gwynedd Council,Apr 14 - Jun 14,NaN
41,Gwynedd Council,Jan 15 - Mar 15,NaN
42,Gwynedd Council,Jul 14 - Sep 14,NaN
43,Gwynedd Council,Oct 14 - Dec 14,NaN
44,Isle of Anglesey CC,Apr 14 - Jun 14,12.400
45,Isle of Anglesey CC,Jan 15 - Mar 15,15.260
46,Isle of Anglesey CC,Jul 14 - Sep 14,1.240
47,Isle of Anglesey CC,Oct 14 - Dec 14,6.780
48,Merthyr Tydfil CBC,Apr 14 - Jun 14,28.660
49,Merthyr Tydfil CBC,Jan 15 - Mar 15,33.160
50,Merthyr Tydfil CBC,Jul 14 - Sep 14,33.880
51,Merthyr Tydfil CBC,Oct 14 - Dec 14,49.820
52,Monmouthshire CC,Apr 14 - Jun 14,11.030
53,Monmouthshire CC,Jan 15 - Mar 15,4.470
54,Monmouthshire CC,Jul 14 - Sep 14,12.080
55,Monmouthshire CC,Oct 14 - Dec 14,16.520
56,Neath Port Talbot CBC,Apr 14 - Jun 14,NaN
57,Neath Port Talbot CBC,Jan 15 - Mar 15,NaN
58,Neath Port Talbot CBC,Jul 14 - Sep 14,NaN
59,Neath Port Talbot CBC,Oct 14 - Dec 14,NaN
60,Newport City Council,Apr 14 - Jun 14,82.900
61,Newport City Council,Jan 15 - Mar 15,64.400
62,Newport City Council,Jul 14 - Sep 14,102.000
63,Newport City Council,Oct 14 - Dec 14,86.700
64,Pembrokeshire County Council,Apr 14 - Jun 14,13.430
65,Pembrokeshire County Council,Jan 15 - Mar 15,12.870
66,Pembrokeshire County Council,Jul 14 - Sep 14,18.070
67,Pembrokeshire County Council,Oct 14 - Dec 14,8.430
68,Powys County Council,Apr 14 - Jun 14,0.840
69,Powys County Council,Jan 15 - Mar 15,1.400
70,Powys County Council,Jul 14 - Sep 14,1.420
71,Powys County Council,Oct 14 - Dec 14,6.063
72,Rhondda Cynon Taff CBC,Apr 14 - Jun 14,NaN
73,Rhondda Cynon Taff CBC,Jan 15 - Mar 15,NaN
74,Rhondda Cynon Taff CBC,Jul 14 - Sep 14,NaN
75,Rhondda Cynon Taff CBC,Oct 14 - Dec 14,NaN
76,Torfaen CBC,Apr 14 - Jun 14,NaN
77,Torfaen CBC,Jan 15 - Mar 15,NaN
78,Torfaen CBC,Jul 14 - Sep 14,NaN
79,Torfaen CBC,Oct 14 - Dec 14,NaN
80,Vale of Glamorgan Council,Apr 14 - Jun 14,NaN
81,Vale of Glamorgan Council,Jan 15 - Mar 15,NaN
82,Vale of Glamorgan Council,Jul 14 - Sep 14,NaN
83,Vale of Glamorgan Council,Oct 14 - Dec 14,NaN
84,Wrexham CBC,Apr 14 - Jun 14,115.150
85,Wrexham CBC,Jan 15 - Mar 15,NaN
86,Wrexham CBC,Jul 14 - Sep 14,NaN
87,Wrexham CBC,Oct 14 - Dec 14,NaN

In [10]:
qu18 = raw[raw['QuestionNumber']=='Q018']
qu18.RowText.unique()
#not relevant i believe

array([ u"Municipal parks/grounds waste collected through 'other' means for composting",
       u'Waste collected in community skips',
       u'Other method of waste / material capture'], dtype=object)

In [12]:
pub_res_la = pub_res_qtr.groupby('Authority').agg(np.sum).reset_index()
pub_fly_la = pub_fly_qtr.groupby('Authority').agg(np.sum).reset_index()

In [23]:
merge = pub_res_la.merge(pub_fly_la, how='left',on='Authority')

In [24]:
merge

RowText,Authority,Collected household waste : Street Cleaning,Waste Arising from clearance of fly-tipped materials
0,Blaenau Gwent CBC,397.610,NaN
1,Bridgend CBC,3397.480,NaN
2,Caerphilly CBC,2197.760,NaN
3,Cardiff County Council,6139.820,1159.560
4,Carmarthenshire County Council,440.800,37.060
5,Ceredigion County Council,3922.860,0.520
6,City and County of Swansea,3740.700,NaN
7,Conwy CBC,2991.680,NaN
8,Denbighshire County Council,237.890,NaN
9,Flintshire County Council,427.896,95.438
10,Gwynedd Council,3496.120,NaN
11,Isle of Anglesey CC,2855.000,35.680
12,Merthyr Tydfil CBC,NaN,145.520
13,Monmouthshire CC,823.440,44.100
14,Neath Port Talbot CBC,2100.000,NaN
15,Newport City Council,1961.000,336.000
16,Pembrokeshire County Council,1386.750,52.800
17,Powys County Council,509.720,9.723
18,Rhondda Cynon Taff CBC,2629.080,NaN
19,Torfaen CBC,134.010,NaN
20,Vale of Glamorgan Council,2336.040,NaN
21,Wrexham CBC,2041.420,115.150

In [25]:
merge = merge.replace(np.NaN, 0)
merge['Litter'] = (merge['Collected household waste : Street Cleaning']/2) - merge['Waste Arising from clearance of fly-tipped materials']

In [26]:
merge

RowText,Authority,Collected household waste : Street Cleaning,Waste Arising from clearance of fly-tipped materials,Litter
0,Blaenau Gwent CBC,397.610,0.000,198.805
1,Bridgend CBC,3397.480,0.000,1698.740
2,Caerphilly CBC,2197.760,0.000,1098.880
3,Cardiff County Council,6139.820,1159.560,1910.350
4,Carmarthenshire County Council,440.800,37.060,183.340
5,Ceredigion County Council,3922.860,0.520,1960.910
6,City and County of Swansea,3740.700,0.000,1870.350
7,Conwy CBC,2991.680,0.000,1495.840
8,Denbighshire County Council,237.890,0.000,118.945
9,Flintshire County Council,427.896,95.438,118.510
10,Gwynedd Council,3496.120,0.000,1748.060
11,Isle of Anglesey CC,2855.000,35.680,1391.820
12,Merthyr Tydfil CBC,0.000,145.520,-145.520
13,Monmouthshire CC,823.440,44.100,367.620
14,Neath Port Talbot CBC,2100.000,0.000,1050.000
15,Newport City Council,1961.000,336.000,644.500
16,Pembrokeshire County Council,1386.750,52.800,640.575
17,Powys County Council,509.720,9.723,245.137
18,Rhondda Cynon Taff CBC,2629.080,0.000,1314.540
19,Torfaen CBC,134.010,0.000,67.005
20,Vale of Glamorgan Council,2336.040,0.000,1168.020
21,Wrexham CBC,2041.420,115.150,905.560

In [27]:
sum(merge['Litter'])

20051.987000000005

#Litter recycling from Q034

In [40]:
litter_rec = raw[(raw.QuestionNumber == 'Q034') & (raw.ColText == 'Tonnage collected for recycling')]

In [41]:
litter_rec.ColText.unique()

array([u'Tonnage collected for recycling'], dtype=object)

In [42]:
litter_rec

,Authority,Period,QuestionNumber,QuText,RowText,ColText,Data,MaterialGroup
974,Ceredigion County Council,Jan 15 - Mar 15,Q034,Tonnes of material collected for recycling at ...,Mixed glass,Tonnage collected for recycling,107.49,Glass
1183,Ceredigion County Council,Oct 14 - Dec 14,Q034,Tonnes of material collected for recycling at ...,Mixed glass,Tonnage collected for recycling,94.92,Glass
1258,Ceredigion County Council,Jul 14 - Sep 14,Q034,Tonnes of material collected for recycling at ...,Mixed glass,Tonnage collected for recycling,133.71,Glass
1327,Ceredigion County Council,Apr 14 - Jun 14,Q034,Tonnes of material collected for recycling at ...,Mixed glass,Tonnage collected for recycling,122.94,Glass
2364,Newport City Council,Jan 15 - Mar 15,Q034,Tonnes of material collected for recycling at ...,Co mingled materials,Tonnage collected for recycling,3.24,Co-mingled

In [43]:
sum(litter_rec['Data'])

462.3

In [45]:
drs_list = ['DRS Glass Bottles','DRS Plastic Bottles','DRS Ferrous Cans','DRS Aluminium Cans','DRS Beverage Cartons']
test = pd.DataFrame(data={'DRS Materials':drs_list,''})
test

          DRS Materials
0     DRS Glass Bottles
1   DRS Plastic Bottles
2      DRS Ferrous Cans
3    DRS Aluminium Cans
4  DRS Beverage Cartons

In [55]:
hhkerb_rec_sum = (massflow_baseline.get_hhkerb_rec_drs().sum(axis=0, numeric_only=True).div(1000).to_frame()
                          .reset_index().rename(columns={'RowText': 'DRS Materials',0: 'Household Kerbside Recycling'}))

In [56]:
hhkerb_rec_sum

          DRS Materials  Household Kerbside Recycling
0     DRS Glass Bottles                     47.312957
1   DRS Plastic Bottles                     20.048890
2      DRS Ferrous Cans                      2.485369
3    DRS Aluminium Cans                      4.097704
4  DRS Beverage Cartons                      0.748891

In [80]:
reload(massflow_baseline)

In [81]:
massflow_baseline.get_massflow_baseline()

,DRS Materials,Total Volume in Thousand Tonnes,Household Kerbside Recycling,Household Kerbside Residual,HWRCs Recycling,HWRCs Residual,Remains in Environment
0,DRS Glass Bottles,95.370,47.312957,8.839449,7.643751,1.132976,0.95370
1,DRS Plastic Bottles,22.542,20.048890,6.542926,1.653019,0.641032,0.22542
2,DRS Ferrous Cans,2.890,2.485369,0.673358,0.250098,0.177158,0.02890
3,DRS Aluminium Cans,5.202,4.097704,1.410412,0.135646,0.240873,0.05202
4,DRS Beverage Cartons,2.890,0.748891,1.603233,0.036783,0.067988,0.02890
5,Total,128.316,NaN,NaN,NaN,NaN,1.28316

In [91]:
reload(massflow_baseline)

In [92]:
baseline = massflow_baseline.get_massflow_baseline()

In [93]:
baseline

,DRS Materials,Total Volume in Thousand Tonnes,Household Kerbside Recycling,Household Kerbside Residual,HWRCs Recycling,HWRCs Residual,Remains in Environment
0,DRS Glass Bottles,95.370,47.312957,8.839449,7.643751,1.132976,0.95370
1,DRS Plastic Bottles,22.542,20.048890,6.542926,1.653019,0.641032,0.22542
2,DRS Ferrous Cans,2.890,2.485369,0.673358,0.250098,0.177158,0.02890
3,DRS Aluminium Cans,5.202,4.097704,1.410412,0.135646,0.240873,0.05202
4,DRS Beverage Cartons,2.890,0.748891,1.603233,0.036783,0.067988,0.02890
5,Total,128.316,74.693810,19.069379,9.719297,2.260028,1.28316

In [87]:
sum(baseline['Household Kerbside Recycling'])

nan